[project]
name = "gaps"
version = "0.1.0"
description = "Genetic Algorithm based solver for jigsaw puzzles with piece size auto-detection."
readme = "README.md"
requires-python = ">=3.12,<3.13"
license = "MIT"
authors = [
    { name = "Nemanja Milicevic", email = "the.nemanja.milicevic@gmail.com" },
]
dependencies = [
    "pillow>=10.2.0,<11.0.0",
    "numpy>=1.26.0,<2.0.0",
    "opencv-python>=4.8.0.76,<5.0.0",
    "click>=8.1.6,<9.0.0",
]

[project.urls]
Homepage = "https://github.com/nemanja-m/gaps"
Repository = "https://github.com/nemanja-m/gaps"

[project.scripts]
gaps = "gaps.cli:cli"

[dependency-groups]
dev = [
    "pytest>=7.4.3,<8.0.0",
    "ruff>=0.1.8,<1.0.0",
    "black>=24.3.0,<25.0.0",
    "mypy>=1.6.1,<2.0.0",
    "pylint>=3.0.2,<4.0.0",
    "pyright>=1.1.414,<2.0.0",
]

[tool.pytest.ini_options]
addopts = "-ra -v"

[tool.black]
target-version = ["py312"]

[tool.ruff]
target-version = "py312"

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
