#!/usr/bin/env python

import argparse
import os.path
parser = argparse.ArgumentParser(description="Create puzzle pieces from input image by random shuffling. Maximum possible rectangle is cropped from original image.",
                                 formatter_class=argparse.RawTextHelpFormatter)


parser.add_argument("image", type=str, help="Input image.")
parser.add_argument("--piece-side", type=int, default=28,
                    help="Side of puzzle piece.\nMin:    20 px\nMax:    64 px\nDefault 28 px")

args = parser.parse_args()

def print_error_messages(errors):
    print
    for message in errors:
        print "\033[31m[ERROR]\033[0m {0}".format(message)
    exit()

errors = []

if not os.path.isfile(args.image):
    errors.append("Image does not exist.")

if args.piece_side < 20:
    errors.append("Minimum piece side is 20 px.")

if args.piece_side > 64:
    errors.append("Maximum piece side is 64 px.")

if len(errors) > 0:
    print_error_messages(errors)
